export const menuItems = [
    {'id': 'US', 'code': '+1'},
    {'id': 'ILS', 'code': '+972'},
    {'id': 'GB', 'code': '+44'},
    {'id': 'FR', 'code': '+33'},
    {'id': 'DE', 'code': '+49'},
    {'id': 'ES', 'code': '+34'},
    {'id': 'IT', 'code': '+39'},
    {'id': 'JP', 'code': '+81'},
    {'id': 'CN', 'code': '+86'},
    {'id': 'KR', 'code': '+82'},
    {'id': 'RU', 'code': '+7'},
    {'id': 'IN', 'code': '+91'},
    {'id': 'BR', 'code': '+55'},
    {'id': 'AU', 'code': '+61'},
    {'id': 'CA', 'code': '+1'},
    {'id': 'MX', 'code': '+52'},
    {'id': 'AR', 'code': '+54'},
    {'id': 'CL', 'code': '+56'},
  ];